### ISSUE TITLE
Need to add parameter --since when running script for first time

### ISSUE THREAD

**Issue by balibou** [planet-winter/ccxt-ohlcv-fetcher#1]
Awesome repo !

I had to add the --since argument when running the script for first time

<img width="987" alt="Screenshot 2019-10-26 at 13 58 37" src="https://user-images.githubusercontent.com/7440159/67619890-ec4e1100-f7f8-11e9-9e33-12a7edb42263.png">

PS: Don't take into account 1.18.1335 it was a print of my ccxt version :)

**Comment by balibou** [comment]
May I get the right to push a P/R please ? :)
I changed codebase to this:

```python3
print('-'*36, ' INFO', '-'*35)
print('Starting with default since value of {}.'.format(DEFAULT_SINCE))
print('-' * 80)
since = exchange.parse8601(DEFAULT_SINCE)
```

**Comment by planet-winter** [comment]
Yes please go ahead! Thanks for the improvement. Might not merge it today though.

**Comment by balibou** [comment]
ahah thx !
<img width="557" alt="Screenshot 2019-10-26 at 16 52 39" src="https://user-images.githubusercontent.com/7440159/67622302-17445f00-f811-11e9-807f-dffb3e6c2e85.png">

still not working :)

**Comment by planet-winter** [comment]
Would it be ok for you to fork and edit in your repo, then send a pull request?
Or I'll just add your fixes later. I am debugging a mailserver currently.

**Comment by balibou** [comment]
No worries I will fork and edit it ;)
