### ISSUE TITLE
Not resuming from last candle fetched

### ISSUE THREAD

**Issue by balibou** [planet-winter/ccxt-ohlcv-fetcher#2]
When I stop and run again the script, it's resuming before last candle fetched.

last fetched:
<img width="616" alt="Screenshot 2019-10-26 at 14 33 21" src="https://user-images.githubusercontent.com/7440159/67620370-fe7e7e00-f7fd-11e9-87bb-81f93c5e160f.png">

re-run script:
<img width="784" alt="Screenshot 2019-10-26 at 14 34 03" src="https://user-images.githubusercontent.com/7440159/67620368-f1618f00-f7fd-11e9-85d0-e4e992c1f0db.png">

PS: Also when I export to a csv file, the last row of the csv is:
`2019-10-25T21:35:00.000Z [1572039300000, 8574.96, 8574.98, 8571.99, 8572.52, 13.239665]`
and not:
`2019-10-26T13:31:00.000Z [1572096660000, 9114.59, 9134.92, 9110.75, 9127.44, 33.021051]`
so my assumption is at some point the data are fetched, but not saved in the database

**Comment by balibou** [comment]
Update: so actually the issue comes from `min_batch_len = DEFAULT_MIN_BATCH_LEN`, I'll do another P/R for this issue.

If I can get the rights to push a pull request ;)

**Comment by planet-winter** [comment]
Yes please go ahead! Merci!

**Comment by planet-winter** [comment]
In the current commit I have removed min_batch_len and batched writing of fetched data altogether. I don't need it anymore. So problem should be fixed.
If you would like to have the feature again please re-introduce it or let me know :)

**Comment by balibou** [comment]
ahah ok @planet-winter !

**Comment by balibou** [comment]
by the way very nice solution with timeframes_difference :) I spent my day trying to do it in another way ahah

**Comment by balibou** [comment]
May I close this issue ?

**Comment by planet-winter** [comment]
Yes sure I'll  do :)

**Comment by balibou** [comment]
@planet-winter Actually you are encountering the same problem I had today :D 
When you fetch data, then stop the script and rerun it, you'll get this error (timestamp fulfilled in database won't be unique):

<img width="774" alt="Screenshot 2019-10-27 at 23 27 51" src="https://user-images.githubusercontent.com/7440159/67643648-830df100-f911-11e9-8700-13e51fb4d1c1.png">
